# Generated by Django 3.1.1 on 2020-09-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectableapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectable',
            name='sold_price',
            field=models.FloatField(null=True),
        ),
    ]
